use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Client {
    pub id: String,
    pub first_name: String,
    pub last_name: String,
    pub middle_name: Option<String>,
    pub dob: Option<String>,
    pub gender: Option<String>,
    pub phone: Option<String>,
    pub phone2: Option<String>,
    pub email: Option<String>,
    pub address_line1: Option<String>,
    pub address_line2: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub zip: Option<String>,
    pub county: Option<String>,
    pub mbi: Option<String>,
    pub part_a_date: Option<String>,
    pub part_b_date: Option<String>,
    pub orec: Option<String>,
    pub esrd_status: Option<i32>,
    pub is_dual_eligible: Option<i32>,
    pub dual_status_code: Option<String>,
    pub lis_level: Option<String>,
    pub medicaid_id: Option<String>,
    pub lead_source: Option<String>,
    pub original_effective_date: Option<String>,
    pub is_active: Option<i32>,
    pub tags: Option<String>,
    pub notes: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateClientInput {
    pub first_name: String,
    pub last_name: String,
    pub middle_name: Option<String>,
    pub dob: Option<String>,
    pub gender: Option<String>,
    pub phone: Option<String>,
    pub phone2: Option<String>,
    pub email: Option<String>,
    pub address_line1: Option<String>,
    pub address_line2: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub zip: Option<String>,
    pub county: Option<String>,
    pub mbi: Option<String>,
    pub part_a_date: Option<String>,
    pub part_b_date: Option<String>,
    pub orec: Option<String>,
    pub esrd_status: Option<i32>,
    pub is_dual_eligible: Option<i32>,
    pub dual_status_code: Option<String>,
    pub lis_level: Option<String>,
    pub medicaid_id: Option<String>,
    pub lead_source: Option<String>,
    pub original_effective_date: Option<String>,
    pub tags: Option<String>,
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateClientInput {
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub middle_name: Option<String>,
    pub dob: Option<String>,
    pub gender: Option<String>,
    pub phone: Option<String>,
    pub phone2: Option<String>,
    pub email: Option<String>,
    pub address_line1: Option<String>,
    pub address_line2: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub zip: Option<String>,
    pub county: Option<String>,
    pub mbi: Option<String>,
    pub part_a_date: Option<String>,
    pub part_b_date: Option<String>,
    pub orec: Option<String>,
    pub esrd_status: Option<i32>,
    pub is_dual_eligible: Option<i32>,
    pub dual_status_code: Option<String>,
    pub lis_level: Option<String>,
    pub medicaid_id: Option<String>,
    pub lead_source: Option<String>,
    pub original_effective_date: Option<String>,
    pub is_active: Option<i32>,
    pub tags: Option<String>,
    pub notes: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientListItem {
    pub id: String,
    pub first_name: String,
    pub last_name: String,
    pub dob: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub zip: Option<String>,
    pub mbi: Option<String>,
    pub is_active: Option<i32>,
    pub is_dual_eligible: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ClientFilters {
    pub search: Option<String>,
    pub carrier_id: Option<String>,
    pub plan_type_code: Option<String>,
    pub status_code: Option<String>,
    pub state: Option<String>,
    pub zip: Option<String>,
    pub is_dual_eligible: Option<bool>,
    pub is_active: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaginatedResult<T: Serialize> {
    pub items: Vec<T>,
    pub total: i64,
    pub page: i32,
    pub per_page: i32,
}
